### ISSUE TITLE
Blitz instance accessing wrong server

### ISSUE THREAD

**Issue by TimmyStorms** [dancres/blitzjavaspaces#2]
Hi,

We've been running 3 servers with each a blitz java space instance on them for many years now. They have been running fine on our old linux servers, but recently we had to switch to newer ones that have a Windows 7 environment. ATM we're seeing a strange issue on 2 of these new servers (our pre-production and production servers, referred to as A and B). The development server (Server C) seems to be unaffected somehow. All servers are configured in the same way (verified that a million times by now...).

The problem starts when the blitz instance on server A is restarted (e.g. after a new depolyment or a server reboot). On server B we will immediately see the following stacktrace. They are thrown every second so log files get cluttered fast! Also note that the same thing happens when Server B is restarted instead of A.

2014-11-07 15:27:59,768 WARN  [OurClassName] RMI problem
java.rmi.ConnectException: Connection refused to host: Server_A_IP; nested exception is: 
    java.net.ConnectException: Connection refused: connect
    at sun.rmi.transport.tcp.TCPEndpoint.newSocket(Unknown Source)
    at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
    at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
    at sun.rmi.server.UnicastRef.invoke(Unknown Source)
    at com.sun.jini.mahalo.TxnManagerImpl_Stub.abort(Unknown Source)
    at com.sun.jini.mahalo.TxnMgrProxy.abort(TxnMgrProxy.java:145)
    at net.jini.core.transaction.server.ServerTransaction.abort(ServerTransaction.java:105)
    at our.application.class
Caused by: java.net.ConnectException: Connection refused: connect
    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.<init>(Unknown Source)
    at java.net.Socket.<init>(Unknown Source)
    at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(Unknown Source)
    at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(Unknown Source)
    ... 8 more

You can image this causes great problems. When we perform an application deployment on Server A, we'll have to restart production Server B and cross our fingers that none of our users experience any problems. Can someone guide me to a setting or at least point me in the right direction? It's frustrating to see that Server A an Server B seem to know about each other, and Server C is isolated as it's supposed to be... Also, there's no problem as long as server A or B keep running. 

Thanks!

**Comment by TimmyStorms** [comment]
@dancres would really like you to have a look at this. Have you heard about similar issue before? Thanks a lot in advance.

**Comment by dancres** [comment]
How are you starting these Blitz instances? Are you using one of the scripts straight out of the installer perhaps or a variation thereof?

**Comment by TimmyStorms** [comment]
Thanks for the fast response! I'm starting blitz with:

java -classpath ".;lib/_;....../jini2_1/lib/_" -Djava.security.policy=....../blitz/policy.all -jar ....../jini2_1/lib/start.jar ....../blitz/config/start-test.config

We probably want to take this offline if you want configuration details.

**Comment by dancres** [comment]
Okay, from your config, I see on each machine you are running Reggie (lookup), Mahalo (Txn Manager) and Blitz in a single JVM.

Looking at the exception above:

at com.sun.jini.mahalo.TxnManagerImpl_Stub.abort(Unknown Source)
at com.sun.jini.mahalo.TxnMgrProxy.abort(TxnMgrProxy.java:145)
at net.jini.core.transaction.server.ServerTransaction.abort(ServerTransaction.java:105)
at our.application.class

It would seem you are using Transactions? If so, I think you are in some way using the transaction manager on one machine to run transactions against a JavaSpace/Blitz instance on another. Under such a circumstance, stopping the Blitz instance would cause the TransactionManager on the other machine to start aborting any in-flight transactions. This requires communicating with the Blitz instance which of course is no longer present. This results in all the exceptions you see.

I believe this is happening because you have some client code somewhere that is in some way obtaining the TransactionManager reference of one machine and the Blitz instance of another. Smells like lookup configuration might be the culprit! Or possibly the join configuration of the Blitz instances.

Note that your current configuration, when you start up allocates whatever sockets are free, not fixed ones. Were services to come back on their original sockets, you would get better behaviour as the TransactionManager would ultimately learn that the transaction was dead and cleanup.
