### ISSUE TITLE
blitz 2.1.7 startup issue

### ISSUE THREAD

**Issue by ekyu88** [dancres/blitzjavaspaces#4]
Hi,

I'm running Blitz 2.1.7 with JINI 2.1 and Java 1.7 and encounter an exception during startup... Any ideas about what's going on?

Feb 06, 2015 1:05:46 PM com.sun.jini.tool.ClassServer run
INFO: ClassServer started [[C:/Projects/JavaSpaces/jini2_1/lib-dl/], port 8081]
reggie-dl.jar requested from nanomat.egi.slc:61954
jsk-dl.jar requested from nanomat.egi.slc:61955
Feb 06, 2015 1:05:47 PM com.sun.jini.reggie.RegistrarImpl init
INFO: started Reggie: 7241823c-d11d-476c-b850-662a3f16c7ee, [], jini://nanomat.egi.slc/
mahalo-dl.jar requested from nanomat.egi.slc:61957
jsk-dl.jar requested from nanomat.egi.slc:61958
Feb 06, 2015 1:05:47 PM com.sun.jini.mahalo.TxnManagerImpl doInit
INFO: Mahalo started: com.sun.jini.mahalo.TransientMahaloImpl@7f745b55
reggie-dl.jar probed from nanomat.egi.slc:61962
Feb 06, 2015 1:05:47 PM com.sun.jini.tool.ClassServer run
INFO: ClassServer started [[C:/Projects/JavaSpaces/Blitz217/lib/], port 8880]
reggie-dl.jar requested from nanomat.egi.slc:61964
blitz-dl.jar requested from nanomat.egi.slc:61963
jsk-dl.jar requested from nanomat.egi.slc:61965
Feb 06, 2015 1:05:47 PM org.dancres.blitz.config.ConfigurationFactory setup
INFO: ConfigurationFactory will load config from: C:/Projects/JavaSpaces/Blitz217/config/blitz.config
Feb 06, 2015 1:05:47 PM org.dancres.blitz.config.ConfigurationFactory load
INFO: Loading config from: C:/Projects/JavaSpaces/Blitz217/config/blitz.config
Feb 06, 2015 1:05:47 PM org.dancres.blitz.txn.PersistentPersonality <init>
INFO: PersistentPersonality
Feb 06, 2015 1:05:47 PM org.dancres.blitz.txn.PersistentPersonality <init>
INFO: Max logs before sync: 10000
Feb 06, 2015 1:05:47 PM org.dancres.blitz.txn.PersistentPersonality <init>
INFO: Reset log stream: true
Feb 06, 2015 1:05:47 PM org.dancres.blitz.txn.PersistentPersonality <init>
INFO: Write barrier window: 0, 500000
Feb 06, 2015 1:05:47 PM org.dancres.blitz.txn.PersistentPersonality <init>
WARNING: **\* Automatically cleaning logs **\* [EXPERIMENTAL]
Feb 06, 2015 1:05:47 PM org.dancres.blitz.disk.Disk <clinit>
INFO: Max txns: 256
Feb 06, 2015 1:05:47 PM org.dancres.blitz.disk.Disk <clinit>
INFO: DbCache: 27262976
Feb 06, 2015 1:05:47 PM org.dancres.blitz.disk.Disk init
INFO: Opening Database
Feb 06, 2015 1:05:48 PM org.dancres.blitz.disk.Disk init
INFO: Database recovery complete
Feb 06, 2015 1:05:48 PM org.dancres.blitz.disk.WriteDaemon <init>
INFO: Async keepalive: 60000
Feb 06, 2015 1:05:48 PM org.dancres.blitz.disk.WriteDaemon <init>
INFO: Pending write size: 256
Feb 06, 2015 1:05:48 PM org.dancres.blitz.disk.WriteDaemon <init>
INFO: Throttle write size: 2147483647
Feb 06, 2015 1:05:48 PM org.dancres.blitz.disk.WriteDaemon <init>
INFO: Throttle pause: 50
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.LookupData dump
INFO: ServiceID: 62e646e8-e0e9-4fed-b3a2-e0d6820e972a
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.LookupData dump
INFO: Groups:
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.LookupData dump
INFO:
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.LookupData dump
INFO: Locators:
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.LookupData dump
INFO: None
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.BlitzServiceImpl initImpl
INFO: Using exporter: BasicJeriExporter[TcpServerEndpoint[0],1d620f2e-93b1-46e6-83ed-6c188cbec189]
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.BlitzServiceImpl initImpl
INFO: Stub supports: org.dancres.blitz.remote.BlitzServer
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.BlitzServiceImpl initImpl
INFO: Stub supports: net.jini.security.proxytrust.ProxyTrust
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.BlitzServiceImpl initImpl
INFO: Stub supports: net.jini.core.constraint.RemoteMethodControl
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.BlitzServiceImpl initImpl
INFO: Stub supports: net.jini.security.proxytrust.TrustEquivalence
Feb 06, 2015 1:05:48 PM org.dancres.blitz.VersionInfo dump
INFO: Version info: Blitz JavaSpaces (PureJavaEdition), blitz@dancres.org, The Blitz Project, 2.1.7, Db/Java 4.1.21
Feb 06, 2015 1:05:48 PM org.dancres.blitz.SpaceImpl <init>
INFO: Synchrounous Notifies: true
Feb 06, 2015 1:05:48 PM org.dancres.blitz.txn.TxnManager recover
INFO: Doing log recovery...
Feb 06, 2015 1:05:48 PM org.dancres.blitz.txn.PersistentReboot execute
INFO: Restoring UnsyncdOps state: 20000
Reading: log\dbfiles_dancres\prevlog\000000000000000000000.snapshot...
Feb 06, 2015 1:05:48 PM org.dancres.blitz.txn.TxnManager recover
INFO: Log Recovery complete...
Feb 06, 2015 1:05:48 PM org.dancres.blitz.txn.TxnManager recover
INFO: Using prevayler: class org.dancres.blitz.txn.batch.ConcurrentWriteBatcher
Feb 06, 2015 1:05:48 PM org.dancres.blitz.notify.EventQueue <init>
INFO: Max Event Processors: 4
Feb 06, 2015 1:05:48 PM org.dancres.blitz.notify.EventQueue <init>
INFO: Event Queue Bound: 0
Feb 06, 2015 1:05:48 PM org.dancres.blitz.oid.AllocatorImpl <init>
INFO: Allocator: BlitzEventGens
Feb 06, 2015 1:05:48 PM org.dancres.blitz.oid.AllocatorImpl <init>
INFO: BlitzEventGens:Resync'ing allocators: 20000
Feb 06, 2015 1:05:48 PM org.dancres.blitz.oid.AllocatorImpl <init>
INFO: Minimum allocator oid for BlitzEventGens: 60001
Feb 06, 2015 1:05:48 PM org.dancres.blitz.notify.EventQueue begin
INFO: Event queue bounding disabled
Feb 06, 2015 1:05:48 PM org.dancres.blitz.lease.LeaseReaper <init>
INFO: Reaper::EntryReaper:theReapTime: 0
Feb 06, 2015 1:05:48 PM org.dancres.blitz.lease.LeaseReaper <init>
INFO: Reaper::EntryReaper:Filter = org.dancres.blitz.TxnReapFilter@5cd12c0c
Feb 06, 2015 1:05:48 PM org.dancres.blitz.config.EntryConstraints <clinit>
INFO: Cache size: 4096
Feb 06, 2015 1:05:48 PM org.dancres.blitz.config.EntryConstraints <clinit>
INFO: Read ahead: 0
Feb 06, 2015 1:05:48 PM org.dancres.blitz.entry.ci.CacheIndexer newIndexer
INFO: Using HASHMAP indexer: java.lang.Object
Feb 06, 2015 1:05:48 PM org.dancres.blitz.entry.SleeveCache <clinit>
INFO: Loaded config: 32
Feb 06, 2015 1:05:48 PM org.dancres.blitz.entry.SleeveCache <init>
INFO: java.lang.Object cache size = 4096 partitions = 128 mask = 7f partition size = 32
Starting Stats Dumper: 60000
Feb 06, 2015 1:05:48 PM org.dancres.blitz.remote.BlitzServiceImpl initImpl
INFO: Space core is up, starting JoinManager
Memory: 255852544 of: 3795320832
nanomat[155.99.184.226]
Thread count: 32
IO TPI: 0.0 TPO: 0.0 IOR: 0.0 QSZ: 0 THROTTLE: 0
Version info: Blitz JavaSpaces (PureJavaEdition), blitz@dancres.org, The Blitz Project, 2.1.7, Db/Java 4.1.21
Active Txns: 0
EventQueue Listeners: transient: 0 persistent: 0
Queue: Events size: 0
Takes:java.lang.Object = 0
Reads:java.lang.Object = 0
Writes:java.lang.Object = 0
Total instance of type java.lang.Object is 0
Store: java.lang.Object Cached miss: 0 deld: 0 Dirty miss: 0 deld: 0 Storage miss: 0 deld: 0 sustainable: false (0, 4096, 204580080,
255852544, 25585254)
Feb 06, 2015 1:05:48 PM com.sun.jini.start.ServiceStarter checkResultFailures
WARNING: Exception creating service.
java.lang.ClassNotFoundException: com.sun.jini.reggie.RegistrarProxy
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at net.jini.loader.pref.PreferredClassProvider.loadClass(PreferredClassProvider.java:613)
        at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
        at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:214)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at java.rmi.MarshalledObject.get(MarshalledObject.java:159)
        at com.sun.jini.start.NonActivatableServiceDescriptor.create(NonActivatableServiceDescriptor.java:644)
        at com.sun.jini.start.ServiceStarter.create(ServiceStarter.java:290)
        at com.sun.jini.start.ServiceStarter.main(ServiceStarter.java:470)

Feb 06, 2015 1:05:48 PM com.sun.jini.start.ServiceStarter checkResultFailures
WARNING: Associated service descriptor [1]: [http://nanomat.egi.slc:8081/reggie-dl.jar http://nanomat.egi.slc:8081/jsk-dl.jar, policy
/policy.all, C:/Projects/JavaSpaces/jini2_1/lib/reggie.jar, com.sun.jini.reggie.TransientRegistrarImpl, [config/reggie.config], com.s
un.jini.start.NonActivatableServiceDescriptor$1@418dad71, BasicProxyPreparer[]]
Feb 06, 2015 1:05:48 PM com.sun.jini.start.ServiceStarter checkResultFailures
WARNING: Exception creating service.
java.lang.ClassNotFoundException: com.sun.jini.mahalo.TxnMgrProxy
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at net.jini.loader.pref.PreferredClassProvider.loadClass(PreferredClassProvider.java:613)
        at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
        at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:214)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at java.rmi.MarshalledObject.get(MarshalledObject.java:159)
        at com.sun.jini.start.NonActivatableServiceDescriptor.create(NonActivatableServiceDescriptor.java:644)
        at com.sun.jini.start.ServiceStarter.create(ServiceStarter.java:290)
        at com.sun.jini.start.ServiceStarter.main(ServiceStarter.java:470)

Feb 06, 2015 1:05:48 PM com.sun.jini.start.ServiceStarter checkResultFailures
WARNING: Associated service descriptor [2]: [http://nanomat.egi.slc:8081/mahalo-dl.jar http://nanomat.egi.slc:8081/jsk-dl.jar, policy
/policy.all, C:/Projects/JavaSpaces/jini2_1/lib/mahalo.jar, com.sun.jini.mahalo.TransientMahaloImpl, [config/mahalo.config], com.sun.
jini.start.NonActivatableServiceDescriptor$1@418dad71, BasicProxyPreparer[]]
Feb 06, 2015 1:05:48 PM com.sun.jini.start.ServiceStarter checkResultFailures
WARNING: Exception creating service.
java.lang.ClassNotFoundException: org.dancres.blitz.remote.ConstrainableBlitzProxy
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:270)
        at net.jini.loader.pref.PreferredClassProvider.loadClass(PreferredClassProvider.java:613)
        at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
        at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:214)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at java.rmi.MarshalledObject.get(MarshalledObject.java:159)
        at com.sun.jini.start.NonActivatableServiceDescriptor.create(NonActivatableServiceDescriptor.java:644)
        at com.sun.jini.start.ServiceStarter.create(ServiceStarter.java:290)
        at com.sun.jini.start.ServiceStarter.main(ServiceStarter.java:470)

Feb 06, 2015 1:05:48 PM com.sun.jini.start.ServiceStarter checkResultFailures
WARNING: Associated service descriptor [4]: [http://nanomat.egi.slc:8880/blitz-dl.jar, C:/Projects/JavaSpaces/Blitz217/config/policy.
all, C:/Projects/JavaSpaces/jini2_1/lib/jsk-lib.jar;C:/Projects/JavaSpaces/jini2_1/lib/sun-util.jar;C:/Projects/JavaSpaces/Blitz217/d
bjava/je.jar;C:/Projects/JavaSpaces/Blitz217/lib/blitz.jar, org.dancres.blitz.remote.BlitzServiceImpl, [C:/Projects/JavaSpaces/Blitz2
17/config/blitz.config], com.sun.jini.start.NonActivatableServiceDescriptor$1@418dad71, BasicProxyPreparer[]]

**Comment by dancres** [comment]
Either classpath or codebase I'd say. As Blitz is able to start and the exceptions all relate to problems with proxy classes I'd favour codebase. And I'd likely start by testing that the codebase URL will resolve and support download so e.g. http://nanomat.egi.slc:8880/blitz-dl.jar and http://nanomat.egi.slc:8081/jsk-dl.jar (two different ports, you need to test both but my suspicion is it'll be hostname/DNS).

**Comment by ekyu88** [comment]
Thanks Dan! The strange thing is that I had the exact exceptions when running Apache River so and both are running in command line... I will dig deeper and see what's happening...

**Comment by dancres** [comment]
Hmm, are you saying you have a fail case and a success case - the latter on the command-line? Can't tell, please clarify...

**Comment by ekyu88** [comment]
Both Apache River and Blitz has the same exception ... Seems to work though for both Java Spaces...

**Comment by dancres** [comment]
I'm still confused - Blitz is a Javaspace :) Everything else that is run via the installer's blitz.sh for example is Apache River.

**Comment by dancres** [comment]
So I think I may have decoded what you're saying. I believe it's that you run them from the command-line, you see exceptions but they don't exit back to the command-line?

If so, for this kind of error, it's normal. The failure is in the ServiceStarter being unable to download the proxies built by the services (Blitz and the Apache bits) - this failure, at first glance, appears to be due to the codebase being invalid hence my recommendations above regarding checking URLs etc.

None of the started virtual machines will exit because the services are up and running, it's just the proxies aren't accessible which can happen for many reasons including temporary network failure (and you wouldn't want your services stopping for that).
